version: 0.2
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands: 
      - echo Build started on `date`
      - echo Building the production Docker image
      - docker build -t podcast-fe:latest ./client
      - docker build -t podcast-be:latest ./simple-backend
  post_build: 
    commands: 
      - echo Pushing the Docker images...
      - docker tag  podcast-fe:latest ${DOCKERHUB_USER}/podcast-fe:latest
      - docker podcast-be:latest ${DOCKERHUB_USER}/podcast-be:latest
      - docker push ${DOCKERHUB_USER}/podcast-fe:latest
      - docker push ${DOCKERHUB_USER}/podcast-be:latest