version: "3.3"
services:
  nginx:
    depends_on:
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    container_name: client


#  FROM BITO
yaml
version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 3000:3000
    restart: on-failure
   server:
    build:
      context: ./simple-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: on-failure