version: "3.3"
services:
  nginx:
    depends_on:
      - client
      - backend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    container_name: client
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    container_name: backend
    environment: 
      - PODCASTS_DB=mongodb+srv://brendan:nolabola@cluster0.l2eyikv.mongodb.net/
