version: '3.8'
services:
  frontend:
    build: ./client
    depends_on:
      - backend
    ports:
      - '7878:3000'
    restart: on-failure
  backend:
    build: ./simple-backend
    ports:
      - '3001:3001'
    restart: on-failure